/* STATUSES */

export const BRANCH_OPEN = 0,
  BRANCH_CLOSED = 1,
  BRANCH_ACCEPTANCE = 2,
  BRANCH_OVERORDERED = 3,
  DELIVERYMAN_AVAILABLE = 0,
  DELIVERYMAN_RETURNING = 1,
  DELIVERYMAN_BREAK = 2,
  DELIVERYMAN_TRANSFER_ORDER = 3,
  DELIVERYMAN_ON_THE_WAY_TO_CLIENT = 4,
  DELIVERYMAN_PICKING_UP_ORDER = 5,
  WORKER_AVAILABLE = 0,
  WORKER_NOT_AVAILABLE = 1,
  WORKER_BREAK = 2,
  WORKER_PREPARING_ORDER = 3,
  ORDER_AWAITING_PREPARATION = 0,
  ORDER_PREPARING = 1,
  ORDER_READY_FOR_PICKUP = 2,
  ORDER_DELIVERING = 3,
  ORDER_DELIVERED = 4,
  ORDER_RETURNED = 5,
  ORDER_PARTLY_RETURNED = 6,
  ORDER_NOT_ACTIVE = 7,
  /* USER TYPES */

  USER_CLIENT = 0,
  USER_WORKER = 1,
  /* ROLES */

  ROLE_TECHNICAL_DIRECTOR = 0,
  ROLE_EXECUTIVE_DIRECTOR = 1,
  ROLE_MANAGER = 2,
  ROLE_WAREHOUSE_WORKER = 3,
  ROLE_DELIVERYMAN = 4,
  ROLE_TECHNICAL_SUPPORT = 5,
  ROLE_CUSTOMER_SUPPORT = 6;
